name = "KernelDensityEstimation"
uuid = "e46ec5f4-66dc-4371-a668-81bd92d19d7d"
authors = ["Justin Willmert <justin@willmert.me>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "1.2"
