name: CI
on:
  push:
    branches: ['master']
    tags: ['*']
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'       # latest release
          - 'pre'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}

      - name: Setup Julia cache
        uses: julia-actions/cache@v3

      - name: Prepare Julia environment
        uses: julia-actions/julia-buildpkg@v1
      - name: Run test suite
        uses: julia-actions/julia-runtest@v1

      - name: Process code coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload code coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info

  mintest:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Minimum-Version Tests
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'     # earliest supported
          - '1.9'     # earliest with pkg extensions
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}

      - name: Setup Julia cache
        uses: julia-actions/cache@v3

      # remove unnecessary dependencies on Julia v1.6 that are only used by package
      # extensions
      - name: Remove package extension dependencies
        if: ${{ matrix.version == '1.6' }}
        run: |
          julia --project=test -e '
          using Pkg
          Pkg.rm(["CairoMakie", "Distributions", "GR", "Makie", "Plots", "UnicodePlots"])
          '

      # test against minimum-declared versions on both the earliest-supported release and
      # the earliest that provides package extensions
      - name: Downgrade dependencies
        uses: julia-actions/julia-downgrade-compat@v1  # @v2 not usable on Julia v1.6
        if: ${{ matrix.version == '1.6' }}
        with:
          projects: .,test
          skip: "LinearAlgebra,Logging,Random,Statistics,Test"
      - name: Downgrade dependencies
        uses: julia-actions/julia-downgrade-compat@v2
        if: ${{ matrix.version == '1.9' }}
        with:
          projects: .,test
          skip: "LinearAlgebra,Logging,Random,Statistics,Test"
          julia_version: ${{ matrix.version }}

      - name: Run test suite
        run: |
          julia --project=test --color=yes -e '
            import Pkg
            Pkg.develop(Pkg.PackageSpec(path=pwd()))
            Pkg.instantiate()
            Pkg.status(; mode=Pkg.PKGMODE_MANIFEST)
            include("test/runtests.jl")
          '

  docs:
    needs: test
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
